export const SIGN_IN_REQUEST = "SIGN_IN_REQUEST";
export const SIGN_OUT_REQUEST = "SIGN_OUT_REQUEST";
export const AUTH_STATE_CHANGED = "AUTH_STATE_CHANGED";
export const CREATE_BUDGET_REQUEST = "CREATE_BUDGET_REQUEST";
export const CREATE_BUDGET_RESPONSE = "CREATE_BUDGET_RESPONSE";
export const CREATE_BUDGET_ERROR = "CREATE_BUDGET_ERROR";
